import wx
import wx.propgrid as wxpg
import numpy as np
import classFunctionModPG as MypgMod
import theme
# ----------------------------------------------------------------------
# Custom SpinCtrlDouble Editor for Float Properties in a wxPropertyGrid. 
# Largely based on answers from qwen3-coder:30b, with earier versions 
# generated by gpt-oss:20B; both LLMs are of Nov. 2025 vintage.
# ----------------------------------------------------------------------
class SpinCtrlDoubleValidator(wx.Validator):
    def __init__(self, min_val=-1e12, max_val=1e12, allow_empty=False):
        super().__init__()
        self.min_val = min_val
        self.max_val = max_val
        self.allow_empty = allow_empty

    def Clone(self):
        return SpinCtrlDoubleValidator(self.min_val, self.max_val, self.allow_empty)
    def Validate(self, win):
        # Get the parent control (should be SpinCtrlDouble)
        ctrl = self.GetWindow()
        if not isinstance(ctrl, wx.SpinCtrlDouble):
            return False
        try:
            value = ctrl.GetValue()
            # Handle empty case
            if value == "" and not self.allow_empty:
                return False
            if value != "":
                float_val = float(value)
                if float_val < self.min_val or float_val > self.max_val:
                    return False
            return True

        except (ValueError, TypeError):
            return False
    def TransferToWindow(self):
        return True
    def TransferFromWindow(self):
        return True

# Custom editor with validator
class SpinCtrlDoubleEditor(wxpg.PGEditor):
    def GetName(self):
        return "SpinCtrlDoubleEditor"

    def CanContainCustomText(self):
        return True

    def CreateControls(self, propGrid, prop, pos, size):
        self.propGrid = propGrid
        
        if propGrid.GetParent().__class__.__name__=='PropGridPanel':
            self.parent = propGrid.GetParent() 
        elif propGrid.GetParent().GetParent().GetParent().__class__.__name__=='PropGridPanel':
            # the propgrid can be in a panel or in a splitwindow that has a parent that is PropGridPanel
            self.parent = propGrid.GetParent().GetParent().GetParent()
            #print('there')
        else:
            print('cannot find my biological parent')
            return False
        self.property = prop

        self.spin = wx.SpinCtrlDouble(propGrid,
                                      style=wx.TE_PROCESS_ENTER|wx.TE_CENTER|wx.SP_ARROW_KEYS)
       
        self.spin.SetRange(-1e12, 1e12)
        inc = prop.GetAttribute(wxpg.PG_ATTR_SPINCTRL_STEP)
        self.spin.SetIncrement(inc)
        self.spin.SetDigits(6)
        self.spin.SetValue(str(prop.GetValue()))
        self.spin.SetPosition(pos)
        self.spin.SetSize(size)

        # Apply custom validator
        validator = SpinCtrlDoubleValidator(-1e12, 1e12)
        self.spin.SetValidator(validator)
        self.property.SetValidator(validator)
        # right-click step menu
        self.spin.Bind(wx.EVT_CONTEXT_MENU, self.ShowStepMenu)
        self.spin.Bind(wx.EVT_RIGHT_DOWN, self.ShowStepMenu)

        # propagate edits
        self.spin.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        
        self.spin.Bind(wx.EVT_TEXT, self.OnText)
        self.spin.Bind(wx.EVT_SPINCTRLDOUBLE, self.OnSpin)
        self.spin.Bind(wx.EVT_TEXT_ENTER, self.OnTextEnter)
        self.spin.Bind(wx.EVT_KILL_FOCUS, self.OnLostFocus)
        theme.theme_control(self.spin)

        return wxpg.PGWindowList(self.spin)
    def OnLostFocus(self, event):
        
        ctrl = event.GetEventObject()
        pg_ctrl = ctrl.GetParent().GetParent()  # PropertyGrid

        if isinstance(pg_ctrl, wxpg.PropertyGrid):
            pg_ctrl.CommitChangesFromEditor()
            pg_ctrl.ClearSelection()
            #print('kill me')
        event.Skip()
        
    def OnKeyDown(self, event):
        key_code = event.GetKeyCode()
        current_value = self.spin.GetValue()
        try:
            current_float = float(current_value)
        except ValueError:
            event.Skip()
            return

        increment = self.spin.GetIncrement()

        if key_code == wx.WXK_UP:
            new_value = current_float + increment
            self.spin.SetValue(str(new_value))
            self.property.SetValue(new_value)
            self.parent.OnValueChanged(event, self.property)
        elif key_code == wx.WXK_DOWN:
            new_value = current_float - increment
            self.spin.SetValue(str(new_value))
            self.property.SetValue(new_value)
            self.parent.OnValueChanged(event, self.property)
        else:
            event.Skip()

    def OnSpin(self, event):
        val = float(self.spin.GetValue())
        prop = self.property
        prop.SetValue(val)
        self.parent.OnValueChanged(event, prop)
        #event.Skip()

    def OnText(self, event):
        txt = self.spin.GetValue()

        try:
            val = float(txt)
        except ValueError:
            return   # allow user to keep typing incomplete values

        prop = self.property
        prop.SetValue(val)
        #self.parent.OnValueChanged(event, prop)
        event.Skip()
    def OnTextEnter(self, event):
        txt = self.spin.GetValue()
        try:
            val = float(txt)
        except ValueError:
            return   # allow user to keep typing incomplete values
        prop = self.property
        prop.SetValue(val)
        self.parent.OnValueChanged(event, prop)
        event.Skip()
        
    def ShowStepMenu(self, evt):
        menu = wx.Menu()
        STEP_VALUES = [
            1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1,
            1, 10, 100, 1000, 1e4, 1e5, 1e6
        ]
        for step in STEP_VALUES:
            menu_item = menu.AppendCheckItem(wx.ID_ANY, f"Set step to {step:g}")
            if step==self.spin.GetIncrement():
                menu_item.Check(True) # Checks the item
            else:
                menu_item.Check(False) # Checks the item
            #item = wx.MenuItem(menu, wx.ID_ANY, f"Set step to {step:g}")
            #menu.Append(item)
            #self.spin.Bind(wx.EVT_MENU, lambda e, s=step: self.spin.SetIncrement(s), item)
            self.spin.Bind(wx.EVT_MENU, lambda e, s=step: self.localSetInc(s), menu_item)
        screen_pos = evt.GetPosition()
        local = self.spin.ScreenToClient(screen_pos)
        self.spin.PopupMenu(menu, local)
        menu.Destroy()
    def localSetInc(self, inc):
        self.spin.SetIncrement(inc)
        self.property.SetAttribute(wxpg.PG_ATTR_SPINCTRL_STEP, inc)
    def UpdateControl(self, property, ctrl):
        pass
        # ctrl.SetValue(float(property.GetValue())) ### this actually makes it impossible to type anything

    def OnEvent(self, propGrid, property, ctrl, event):
#### we don't need any of these actually. These events just trigger more code executions... at least in python at this point. 
        #         et = event.GetEventType()
# # wx.EVT_SPINCTRLDOUBLE.evtType[0],
# #           wx.EVT_KEY_DOWN.evtType[0],
          
#         if et in (wx.EVT_TEXT.evtType[0],
#                   wx.EVT_CHAR.evtType[0]):
#             #keycode = event.GetKeyCode()
#             #print(keycode)
#             property.SetValue(ctrl.GetValue())
#             return True
        return False ### False= value has not been changed, no need to trigger the respective event

    def GetValueFromControl(self, property, ctrl):
        try:
            return (True, float(ctrl.GetValue()))
        except ValueError:
            return (False, property.GetValue())
# import wx
# import wx.propgrid as wxpg

# class StringEnumProperty(wxpg.EnumProperty):
# #    EnumProperty that treats its value as the *label string* instead of the index.
#     def __init__(self, label, name, labels, value=None):
#         if value is None:
#             idx = 0
#         else:
#             try:
#                 idx = labels.index(value)
#             except:
#                 idx = 0
#         super().__init__(label, name, labels, idx)
#         self.SetValue(value)

#     # -----------------------------------------------------------
#     # Return the selected LABEL (string)
#     # -----------------------------------------------------------
#     def GetValue(self):
#         # self.GetValue() from base class returns the integer value (index or enum value)
#         int_val = super().GetValue()
#         # Convert integer → label string
#         idx = self.GetIndexForValue(int_val)
#         return self.GetChoiceStrings()[idx]

#     # -----------------------------------------------------------
#     # Accept a LABEL string and update the underlying integer value
#     # -----------------------------------------------------------
#     def SetValue(self, value):
#       
#  if isinstance(value, str):
#             labels = self.GetChoiceStrings()
#             if value in labels:
#                 idx = labels.index(value)  # label → index
#                 int_val = self.GetValueByIndex(idx)  # index → internal integer enum value
#                 return super().SetValue(int_val)
#             else:
#                 raise ValueError(f"'{value}' is not a valid choice: {labels}")
#         else:
#             # If someone passes an integer, fall back to normal enum behavior
#             return super().SetValue(value)

# -------------------------------------------------------
#   We put everything on a panel. Kind of safer that way, allowing for more versatility of deployment
# -------------------------------------------------------
class PropGridPanel(wx.Panel):
    def __init__(self, parent, Prop_Dict={}, onChangeFunc=None, onUpdate=None, showModFunc = False, *args, **kwargs):
        super().__init__(parent, *args, **kwargs)
        sizer = wx.BoxSizer(wx.VERTICAL)
        
        self.parameters = {}
        self.tooltips = {}
        self.onChangeFunc = onChangeFunc
        self.onUpdate = onUpdate
        self.increment = {}
        self.debug = False
        self.current_sash = 200
        if showModFunc:
            self.splitter = wx.SplitterWindow(self, style=wx.SP_3D)
            self.parentpanel = wx.Panel(self.splitter)
            self.func_panel=MypgMod.FunctionModPanel(self.splitter, 
                                                     PropertyGridPanel = self, 
                                                     style = wx.SUNKEN_BORDER)
            sizer.Add(self.splitter, 1, wx.EXPAND)
            self.parameters['functions'] = {}
        else:
            self.splitter = None
            self.func_panel = None
            self.parentpanel = self
            
            
        self.pg = wxpg.PropertyGrid(
            self.parentpanel,
            style=wxpg.PG_SPLITTER_AUTO_CENTER | wxpg.PG_AUTO_SORT | wx.TAB_TRAVERSAL | wxpg.PG_NO_INTERNAL_BORDER,

        ) #wxpg.PG_HIDE_MARGIN |
        theme.theme_propgrid(self.pg, caption_key="accent")

        if showModFunc:
            insizer = wx.BoxSizer(wx.VERTICAL)
            insizer.Add(self.pg, 1, wx.EXPAND)
            self.btn_sash = wx.Button(self.parentpanel, label="▼", size=(-1, 15))
            self.btn_sash.Bind(wx.EVT_BUTTON, self.adjustSash)
            insizer.Add(self.btn_sash, 0, wx.EXPAND, 0)
            self.parentpanel.SetSizer(insizer)
            
            self.splitter.SplitHorizontally(
                self.parentpanel, self.func_panel,
                sashPosition=self.current_sash   # initial height of the top pane
            )
            self.splitter.SetSashGravity(0)
            
            
        else:
            sizer.Add(self.pg, 1, wx.EXPAND)
        
        self.SetSizer(sizer)
        self.Layout()        
        # self.pg.SetExtraStyle(pg.PG_EX_)
        ## this is important to suppress native menue and allow spinctrl to get its own goind
        self.pg.Bind(wx.EVT_CONTEXT_MENU, lambda evt: None) #
        self.pg.Bind(wxpg.EVT_PG_CHANGED, self.OnValueChanged)
        # Register custom editor
        if not self.pg.GetEditorByName("SpinFloat"):
            self.pg.RegisterEditor(SpinCtrlDoubleEditor, "SpinFloat")
        
        if type(Prop_Dict)!=type(None):
            if len(Prop_Dict)>0:
                self.SetPropsClean(Prop_Dict)
        

        
    def adjustSash(self, event):
        if self.btn_sash.GetLabel()=="▼": 
            self.current_sash = self.splitter.GetSashPosition()
            self.splitter.Unsplit(self.func_panel)
            self.btn_sash.SetLabel("▲")
            
            # self.splitter.SetSashPosition(self.GetSize()[1])
            # self.splitter.SetSashGravity(1)
        else:
            self.splitter.SplitHorizontally(self.parentpanel, self.func_panel, self.current_sash)
            # self.splitter.SetSashPosition(self.current_sash)
            self.btn_sash.SetLabel("▼")
            # self.splitter.SetSashGravity(0)
    
    def OnValueChanged(self, event, prop=None, trigger_run=True):
        if type(event)==wx._core.SpinDoubleEvent:
            if type(prop)==type(None):
                raise AttributeError("😭 Somehow SpinDoubleEvent did not provide property handle. No idea what to do ... figure it out") 
        if type(event)==wx._core.CommandEvent:
            pg = event.EventObject.GetParent()
            prop = pg.GetSelection()
        else:
            if type(prop)==type(None):
                prop = event.GetProperty()
        
        parent = prop.GetParent()
        if self.debug: print(f"{prop.GetName()} = {prop.GetValue()}")
        
            
        if len(self.parameters)>0:
            if '(' in prop.GetName(): ### there is zero chance this is an Enum
                parname = prop.GetName().split('(')[0]# name has to be unique accross the control
                parlabel = prop.GetLabel().split('(')[0]# label only has to be unique within a tree branch

                resparname = prop.GetName().split(')')[1] # there may be a residual, like A(0)0

                if parent.GetName()=='<Root>':
                    for ii in range(len(self.parameters[parlabel])):
                        ppoo = parent.GetPropertyByName(f'{parname}({ii}){resparname}')
                        value = ppoo.GetValue()
                        self.parameters[parlabel][ii] = value
                else:
                    for ii in range(len(self.parameters[parent.GetLabel()][parlabel])):
                        ppoo = parent.GetPropertyByName(f'{parname}({ii}){resparname}')
                        value = ppoo.GetValue()
                        self.parameters[parent.GetLabel()][parlabel][ii] = value
            else:
                # Enum needs to be stores with a [value, choices] style
                if type(prop)==wx._propgrid.EnumProperty:
                    ll = []
                    for ii in range(prop.GetItemCount()):
                       ll.append(prop.ValueToString(ii))
                    value= [prop.GetValueAsString(), ll]
                else:
                    value = prop.GetValue()

                if parent.GetName()=='<Root>':
                    self.parameters[prop.GetLabel()] = value
                else:
                    self.parameters[parent.GetLabel()][prop.GetLabel()] = value
        
        if type(self.onChangeFunc)!=type(None) and trigger_run:
            self.onChangeFunc(parent.GetLabel(), prop.GetLabel(), value)
        if self.debug: print(self.parameters)

    def SetProps(self, Props):
        cat= []
        ncat = 0
        for dd in Props:
            name = dd['name']
            if self.pg.GetPropertyByName(name):
                cnt=0
                while self.pg.GetPropertyByName(name+cnt):
                    cnt+=1
                name=name+cnt
            
            label= dd['label']
            typ  = dd['type']
            value= dd['value']
            choic= dd['choices']
            if label in self.tooltips:
                ttips = self.tooltips[label]
            else:
                ttips = ''

            if typ=='float':
                pro = self.pg.Append(wxpg.FloatProperty(name=name, label=label, value=value))
                self.pg.SetPropertyEditor(name, "SpinFloat")
                pro.SetAttribute(wxpg.PG_ATTR_SPINCTRL_STEP, 0.001)
                pro.SetHelpString(ttips)
            elif typ=='int':
                pro = self.pg.Append(wxpg.IntProperty(name=name, label=label, value=value))
                pro.SetHelpString(ttips)
            elif typ=='string':
                pro = self.pg.Append(wxpg.StringProperty(name=name, label=label, value=value))
                pro.SetHelpString(ttips)
            elif typ=='bool':
                pro = self.pg.Append(wxpg.BoolProperty(name=name, label=label, value=value))
                pro.SetHelpString(ttips)
            elif typ=='colour':
                clr = wxpg.ColourProperty(name=name, label=label, value=value)
                clr.SetAttribute(wxpg.PG_COLOUR_HAS_ALPHA, True)
                self.pg.Append(clr)
                clr.SetHelpString(ttips)
                #, flags=wxpg.PG_COLOUR_HAS_ALPHA
            elif typ=='choices':
                #self.pg.Append(wxpg.MultiChoiceProperty(name=name, label=label, value=value,choises=choic))
                pro = self.pg.Append(wxpg.EnumProperty(name=name, label=label, labels=choic, value=value))
                pro.SetHelpString(ttips)
            elif typ=='dict':
                pro=cat.append(self.pg.Append(wxpg.PropertyCategory(name)))
                cat[ncat].SetHelpString(ttips)
                for ee in value:
                    name1 = ee['name']
                    if self.pg.GetPropertyByName(name1):
                        cnt=0
                        while self.pg.GetPropertyByName(name1+str(cnt)):
                            cnt+=1
                        name1=name1+str(cnt)
                        
                    label1= ee['label']
                    typ1  = ee['type']
                    value1= ee['value']
                    choic1= ee['choices']
                    if label in self.tooltips:
                        ttips = self.tooltips[label]
                    else:
                        ttips = ''

                    if typ1=='float':
                        pro=self.pg.AppendIn(cat[ncat], wxpg.FloatProperty(name=name1, label=label1, value=value1))
                        self.pg.SetPropertyEditor(name1, "SpinFloat")
                        pro.SetAttribute(wxpg.PG_ATTR_SPINCTRL_STEP, 0.001)
                        pro.SetHelpString(ttips)
                    elif typ1=='int':
                        pro = self.pg.AppendIn(cat[ncat], wxpg.IntProperty(name=name1, label=label1, value=value1))
                        pro.SetHelpString(ttips)
                    elif typ1=='string':
                        pro = self.pg.AppendIn(cat[ncat], wxpg.StringProperty(name=name1, label=label1, value=value1))
                        pro.SetHelpString(ttips)
                    elif typ1=='bool':
                        pro = self.pg.AppendIn(cat[ncat], wxpg.BoolProperty(name=name1, label=label1, value=value1))
                        pro.SetHelpString(ttips)
                    elif typ1=='colour':
                        clr =wxpg.ColourProperty(name=name1, label=label1, value=value1)
                        clr.SetAttribute(wxpg.PG_COLOUR_HAS_ALPHA, True)
                        clr.SetHelpString(ttips)
                        self.pg.AppendIn(cat[ncat], clr)
                    elif typ1=='choices':
                        #self.pg.AppendIn(cat[ncat], wxpg.MultiChoiceProperty(name=name, label=label, value=value,choises=choic))
                        pro = self.pg.Append(wxpg.EnumProperty(name=name1, label=label1, labels=choic1, value=value1))
                        pro.SetHelpString(ttips)
                ncat+=1
            elif typ=='functions':
                if self.func_panel is not None:
                    self.func_panel.set_dict(value, clean=True)
            else:
                pass
    def Clear(self):
        self.pg.Clear()
        self.parameters = {}
    def SetFromParClean(self, par):
        self.Clear()
        self.parameters = par
        if type(par)!=dict:
            if self.debug: print(par)
            raise AttributeError("😭 input is not a valid dictionary") 
        outDict = self.to_PropDict(par)
        self.SetProps(outDict)   

    def GetDefaultDictionary(self):
            return {'my_str': 'Main_name (1)',
                    'my_array': np.array([1.0, 2.0, 3.0]),
                    'my_int': int(2),
                    'my_float': float(2),
                    'my_col':wx.Colour(wx.RED),
                    'you':
                        {'you_int': int(1),
                        'you_true': False,
                        'you_type': 'float',
                        'you_value': 1.25,
                        'you_choices': ['choice2', ['choice1', 'choice2', 'choice3']]},

                    }
    def to_PropDict(self, par):
        outDict = []
        for key in par.keys():
            if type(par[key])==str:
                outDict.append(
                    {'name': key,
                   'label': key,
                   'type': 'string',
                   'value': par[key],
                   'choices': []}
                )
            elif (type(par[key])==float):
                outDict.append(
                    {'name': key,
                   'label': key,
                   'type': 'float',
                   'value': par[key],
                   'choices': []}
                )
            elif (type(par[key])==int):
                outDict.append(
                    {'name': key,
                   'label': key,
                   'type': 'int',
                   'value': par[key],
                   'choices': []}
                )    
            elif (type(par[key])==bool):
                outDict.append(
                    {'name': key,
                   'label': key,
                   'type': 'bool',
                   'value': par[key],
                   'choices': []}
                )    
            elif type(par[key])==np.ndarray:
                if len(par[key].shape)==1:
                    for ii in range(par[key].shape[0]):
                        outDict.append(
                                {'name': '%s(%d)'%(key,ii),
                                 'label': '%s(%d)'%(key,ii+1),
                                 'type': 'float',
                                 'value': par[key][ii],
                                 'choices': []}
                            )
                elif len(par[key].shape)==2:
                    for ii in range(par[key].shape[0]):
                        for jj in range(par[key].shape[1]):
                            outDict.append(
                                {'name': '%s(%d,%d)'%(key,ii,jj),
                                 'label': '%s(%d,%d)'%(key,ii+1,jj+1),
                                 'type': 'float',
                                 'value': par[key][ii],
                                 'choices': []}
                            )
                else:
                    raise AttributeError(f"😭 {key} is of higher dimention than we can handle") 
            elif type(par[key])==dict:
                if key=='functions':
                    outDict.append({'name': key,
                         'label': key,
                         'type': 'functions',
                         'value': par[key],
                         'choices': []}
                                   )
                else:
                    depDict = self.to_PropDict(par[key])
                    outDict.append(
                            {'name': key,
                             'label': key,
                             'type': 'dict',
                             'value': depDict,
                             'choices': []}
                        )
            elif type(par[key])==wx._core.Colour:
                outDict.append(
                    {'name': key,
                   'label': key,
                   'type': 'colour',
                   'value': par[key],
                   'choices': []}
                )
            ### PROBLEM: we only have a list in here. how do I get the default value? expect first value to be the current one 
            elif type(par[key])==list:
                hasChoices = False
                if len(par[key])==2:
                    if type(par[key][1])==list:
                        hasChoices = True
                if hasChoices:
                    try:
                        value = par[key][1].index(par[key][0])
                    except:
                        value=0
                    choices= par[key][1]
                else:
                    value=0
                    choices = par[key]

                outDict.append(
                    {'name': key,
                      'label': key,
                      'type': 'choices',
                      'value': value,
                      'choices': choices}
                     )
        return outDict
# -------------------------------------------------------
#   Run Application
# -------------------------------------------------------
if __name__ == "__main__":
    app = wx.App(False)
    frame = wx.Frame(None, size=(800, 800))
    pg = PropGridPanel(frame, showModFunc=True)
    pg.debug = True
    prop=pg.GetDefaultDictionary()
    pg.SetFromParClean(prop)
    frame.Show()
    app.MainLoop()